export const PAGES = {
  home: 'home',
  login: 'login',
  tujuan: 'tujuan',
  menu: 'menu',
  materi_diagram: 'materi_diagram',
  materi_definisi: 'materi_definisi',
  langkah: 'langkah',
  sim_sensorik: 'sim_sensorik',
  sim_penghubung: 'sim_penghubung',
  sim_motorik: 'sim_motorik',
  soal_1: 'soal_1',
  soal_2: 'soal_2',
  soal_3: 'soal_3',
  soal_4: 'soal_4',
  soal_5: 'soal_5',
  soal_6: 'soal_6',
  soal_7: 'soal_7',
  soal_8: 'soal_8',
  soal_9: 'soal_9',
  soal_10: 'soal_10',
  soal_11_esai: 'soal_11_esai',
  skor: 'skor',
  dafpus: 'dafpus',
};